version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: local_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  backend:
    build:
      context: ../../app/backend
      dockerfile: Dockerfile
    container_name: local_backend
    ports:
      - "8000:8000"
    volumes:
      - ../../app/backend:/app 
      - /app/.venv
    env_file:
      - ../../app/backend/.env
    environment:
      - MONGO_URI=mongodb://mongodb:27017/image_db 
    depends_on:
      - mongodb
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge