runtime: python311  # We use the python runtime just to serve static assets efficiently
service: default

handlers:
# 1. Route requests for static assets directly to Vite's output folder
- url: /assets
  static_dir: dist/assets

# 2. Route absolutely all other web traffic to your main index.html file
- url: /.*
  static_files: dist/index.html
  upload: dist/index.html